openapi: 3.2.0
info:
  title: Grafana Comments API
  description: Grafana is an open-source analytics and visualization platform that helps you monitor and analyze data from various sources.
  contact:
    name: Grafana Labs
    url: https://grafana.com
    email: hello@grafana.com
  version: 0.0.1
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com/api
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com/api
security:
- basic: []
- api_key: []
tags:
- name: Comments
paths:
  /query-history/{query_history_uid}:
    parameters: []
    patch:
      tags:
      - Comments
      summary: Grafana Patch Query Comment
      description: Updates the comment of a specific query in the query history by its unique identifier. This endpoint allows users to modify the descriptive comment associated with a previously executed query, making it easier to document and organize query history. The operation requires the query history UID as a path parameter and accepts the updated comment data in the request body. This is useful for adding context, notes, or explanations to queries after they have been run, improving collaboration and query management within Grafana.
      operationId: patchQueryComment
      parameters:
      - name: query_history_uid
        in: path
        description: ''
        required: true
        schema:
          type: string
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchQueryCommentInQueryHistoryCommand'
        required: true
      responses:
        '200':
          description: (empty)
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryHistoryResponse'
        '400':
          description: BadRequestError is returned when the request is invalid and it cannot be processed.
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        '401':
          description: UnauthorizedError is returned when the request is not authenticated.
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        '500':
          description: InternalServerError is a general error indicating something went wrong internally.
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
      deprecated: false
      x-api-evangelist-processing:
        SplitPascalCaseOperationSummaries: true
        CaselCaseOperationIds: true
        WriteDescription: true
        ChooseTags: true
components:
  schemas:
    QueryHistoryResponse:
      title: QueryHistoryResponse
      type: object
      properties:
        result:
          $ref: '#/components/schemas/QueryHistoryDTO'
      description: QueryHistoryResponse is a response struct for QueryHistoryDTO
    ErrorResponseBody:
      title: ErrorResponseBody
      required:
      - message
      type: object
      properties:
        error:
          type: string
          description: Error An optional detailed description of the actual error. Only included if running in developer mode.
        message:
          type: string
          description: a human readable version of the error
        status:
          type: string
          description: 'Status An optional status to denote the cause of the error.


            For example, a 412 Precondition Failed error may include additional information of why that error happened.'
    QueryHistoryDTO:
      title: QueryHistoryDTO
      type: object
      properties:
        comment:
          type: string
        createdAt:
          type: integer
          contentEncoding: int64
        createdBy:
          type: integer
          contentEncoding: int64
        datasourceUid:
          type: string
        queries:
          type: object
        starred:
          type: boolean
        uid:
          type: string
    PatchQueryCommentInQueryHistoryCommand:
      title: PatchQueryCommentInQueryHistoryCommand
      type: object
      properties:
        comment:
          type: string
          description: Updated comment
      description: PatchQueryCommentInQueryHistoryCommand is the command for updating comment for query in query history
  securitySchemes:
    api_key:
      type: apiKey
      name: Authorization
      in: header
    basic:
      type: http
      scheme: basic
